[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "DecentSampler"
authors = [{name = "David Hilowitz", email = "dave@decentsamples.com"}]
dynamic = ["version", "description"]
